source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'OhanaExample' do
  pod 'Ohana', :path => '../'
end

target 'OhanaTests' do
  pod 'Ohana', :path => '../'

  pod 'OCMock', '~> 3.3'
end
